// Generated file. Do not edit manually.

class Clock {
  final String id;
  final String timezone;
  final String name;
  final String country;

  const Clock({
    required this.id,
    required this.timezone,
    required this.name,
    required this.country,
  });
}

const List<Clock> clocks = [
  Clock(id: "C1", timezone: "Africa/Abidjan", name: "Abidjan", country: "Côte d\'Ivoire"),
  Clock(id: "C2", timezone: "Africa/Accra", name: "Accra", country: "Ghana"),
  Clock(id: "C3", timezone: "Africa/Addis_Ababa", name: "Addis Ababa", country: "Ethiopia"),
  Clock(id: "C4", timezone: "Africa/Algiers", name: "Algiers", country: "Algeria"),
  Clock(id: "C5", timezone: "Africa/Blantyre", name: "Blantyre", country: "Malawi"),
  Clock(id: "C6", timezone: "Africa/Brazzaville", name: "Brazzaville", country: "Republic of the Congo"),
  Clock(id: "C7", timezone: "Africa/Cairo", name: "Cairo", country: "Egypt"),
  Clock(id: "C8", timezone: "Africa/Casablanca", name: "Casablanca", country: "Morocco"),
  Clock(id: "C9", timezone: "Africa/Conakry", name: "Conakry", country: "Guinea"),
  Clock(id: "C10", timezone: "Africa/Dakar", name: "Dakar", country: "Senegal"),
  Clock(id: "C11", timezone: "Africa/Dar_es_Salaam", name: "Dar es Salaam", country: "Tanzania"),
  Clock(id: "C12", timezone: "Africa/Djibouti", name: "Djibouti", country: "Djibouti"),
  Clock(id: "C13", timezone: "Africa/Freetown", name: "Freetown", country: "Sierra Leone"),
  Clock(id: "C14", timezone: "Africa/Gaborone", name: "Gaborone", country: "Botswana"),
  Clock(id: "C15", timezone: "Africa/Harare", name: "Harare", country: "Zimbabwe"),
  Clock(id: "C16", timezone: "Africa/Johannesburg", name: "Johannesburg", country: "South Africa"),
  Clock(id: "C17", timezone: "Africa/Kampala", name: "Kampala", country: "Uganda"),
  Clock(id: "C19", timezone: "Africa/Kigali", name: "Kigali", country: "Rwanda"),
  Clock(id: "C20", timezone: "Africa/Kinshasa", name: "Kinshasa", country: "Democratic Republic of the Congo"),
  Clock(id: "C21", timezone: "Africa/Lagos", name: "Lagos", country: "Nigeria"),
  Clock(id: "C22", timezone: "Africa/Maseru", name: "Maseru", country: "Lesotho"),
  Clock(id: "C23", timezone: "Africa/Mogadishu", name: "Mogadishu", country: "Somalia"),
  Clock(id: "C25", timezone: "Africa/Sao_Tome", name: "Sao Tome", country: "Sao Tome and Principe"),
  Clock(id: "C26", timezone: "Africa/Timbuktu", name: "Timbuktu", country: "Mali"),
  Clock(id: "C27", timezone: "Africa/Tripoli", name: "Tripoli", country: "Libya"),
  Clock(id: "C28", timezone: "Africa/Tunis", name: "Tunis", country: "Tunis"),
  Clock(id: "C29", timezone: "America/Anchorage", name: "Anchorage", country: "United States"),
  Clock(id: "C30", timezone: "America/Argentina/Mendoza", name: "Mendoza", country: "Argentina"),
  Clock(id: "C31", timezone: "America/Aruba", name: "Aruba", country: "Aruba"),
  Clock(id: "C32", timezone: "America/Asuncion", name: "Asunción", country: "Paraguay"),
  Clock(id: "C33", timezone: "America/Barbados", name: "Barbados", country: "Barbados"),
  Clock(id: "C34", timezone: "America/Belize", name: "Belize", country: "Belize"),
  Clock(id: "C35", timezone: "America/Bogota", name: "Bogotá", country: "Colombia"),
  Clock(id: "C36", timezone: "America/Buenos_Aires", name: "Buenos Aires", country: "Argentina"),
  Clock(id: "C37", timezone: "America/Cancun", name: "Cancun", country: "Mexico"),
  Clock(id: "C38", timezone: "America/Caracas", name: "Caracas", country: "Venezuela"),
  Clock(id: "C39", timezone: "America/Cayman", name: "Cayman Islands", country: "Cayman Islands"),
  Clock(id: "C40", timezone: "America/Chicago", name: "Chicago", country: "United States"),
  Clock(id: "C41", timezone: "America/Costa_Rica", name: "Costa Rica", country: "Costa Rica"),
  Clock(id: "C42", timezone: "America/Curacao", name: "Curaçao", country: "Curaçao"),
  Clock(id: "C43", timezone: "America/Dawson_Creek", name: "Dawson Creek", country: "Canada"),
  Clock(id: "C44", timezone: "America/Denver", name: "Denver", country: "United States"),
  Clock(id: "C45", timezone: "America/Detroit", name: "Detroit", country: "United States"),
  Clock(id: "C46", timezone: "America/Dominica", name: "Dominican Republic", country: "Dominican Republic"),
  Clock(id: "C47", timezone: "America/Edmonton", name: "Edmonton", country: "Canada"),
  Clock(id: "C48", timezone: "America/El_Salvador", name: "El Salvador", country: "El Salvador"),
  Clock(id: "C49", timezone: "America/Fortaleza", name: "Fortaleza", country: "Brazil"),
  Clock(id: "C50", timezone: "America/Grand_Turk", name: "Grand Turk", country: "Turks and Caicos Islands"),
  Clock(id: "C51", timezone: "America/Grenada", name: "Grenada", country: "Grenada"),
  Clock(id: "C52", timezone: "America/Guatemala", name: "Guatemala", country: "Guatemala"),
  Clock(id: "C53", timezone: "America/Guyana", name: "Guyana", country: "Guyana"),
  Clock(id: "C54", timezone: "America/Halifax", name: "Halifax", country: "Canada"),
  Clock(id: "C55", timezone: "America/Havana", name: "Havana", country: "Cuba"),
  Clock(id: "C56", timezone: "America/Indiana/Indianapolis", name: "Indianapolis", country: "United States"),
  Clock(id: "C57", timezone: "America/Indiana/Knox", name: "Knox", country: "United States"),
  Clock(id: "C58", timezone: "America/Indiana/Marengo", name: "Marengo", country: "United States"),
  Clock(id: "C59", timezone: "America/Indiana/Petersburg", name: "Petersburg", country: "United States"),
  Clock(id: "C60", timezone: "America/Indiana/Tell_City", name: "Tell City", country: "United States"),
  Clock(id: "C61", timezone: "America/Indiana/Vevay", name: "Vevay", country: "United States"),
  Clock(id: "C62", timezone: "America/Indiana/Vincennes", name: "Vincennes", country: "United States"),
  Clock(id: "C63", timezone: "America/Indiana/Winamac", name: "Winamac", country: "United States"),
  Clock(id: "C64", timezone: "America/Jamaica", name: "Kingston", country: "Jamaica"),
  Clock(id: "C65", timezone: "America/La_Paz", name: "Nuestra Señora de La Paz", country: "Bolivia"),
  Clock(id: "C66", timezone: "America/Lima", name: "Lima", country: "Peru"),
  Clock(id: "C67", timezone: "America/Los_Angeles", name: "Los Angeles", country: "United States"),
  Clock(id: "C68", timezone: "America/Louisville", name: "Louisville", country: "United States"),
  Clock(id: "C69", timezone: "America/Managua", name: "Managua", country: "Nicaragua"),
  Clock(id: "C70", timezone: "America/Martinique", name: "Martinique", country: "Martinique"),
  Clock(id: "C71", timezone: "America/Metlakatla", name: "Metlakatla", country: "United States"),
  Clock(id: "C72", timezone: "America/Mexico_City", name: "Mexico City", country: "Mexico"),
  Clock(id: "C73", timezone: "America/Monterrey", name: "Monterey", country: "United States"),
  Clock(id: "C74", timezone: "America/Montevideo", name: "Montevideo", country: "Uruguay"),
  Clock(id: "C75", timezone: "America/Montreal", name: "Montreal", country: "Canada"),
  Clock(id: "C76", timezone: "America/Nassau", name: "Nassau", country: "Bahamas"),
  Clock(id: "C77", timezone: "America/New_York", name: "New York", country: "United States"),
  Clock(id: "C78", timezone: "America/North_Dakota/Beulah", name: "Beulah", country: "United States"),
  Clock(id: "C79", timezone: "America/North_Dakota/Center", name: "Center", country: "United States"),
  Clock(id: "C80", timezone: "America/North_Dakota/New_Salem", name: "New Salem", country: "United States"),
  Clock(id: "C81", timezone: "America/Panama", name: "Panama", country: "Panama"),
  Clock(id: "C82", timezone: "America/Phoenix", name: "Phoenix", country: "United States"),
  Clock(id: "C83", timezone: "America/Port_of_Spain", name: "Port of Spain", country: "Trinidad and Tobago"),
  Clock(id: "C84", timezone: "America/Port-au-Prince", name: "Port-au-Prince", country: "Haiti"),
  Clock(id: "C85", timezone: "America/Puerto_Rico", name: "Puerto Rico", country: "Puerto Rico"),
  Clock(id: "C86", timezone: "America/Santo_Domingo", name: "Santo Domingo", country: "Dominican Republic"),
  Clock(id: "C87", timezone: "America/Sao_Paulo", name: "São Paulo", country: "Brazil"),
  Clock(id: "C88", timezone: "America/St_Johns", name: "St. John\'s", country: "Canada"),
  Clock(id: "C89", timezone: "America/St_Kitts", name: "St. Kitts", country: "Saint Kitts and Nevis"),
  Clock(id: "C90", timezone: "America/St_Lucia", name: "Saint Lucia", country: "Saint Lucia"),
  Clock(id: "C91", timezone: "America/St_Thomas", name: "St. Thomas", country: "U.S. Virgin Islands"),
  Clock(id: "C92", timezone: "America/Tijuana", name: "Tijuana", country: "Mexico"),
  Clock(id: "C93", timezone: "America/Toronto", name: "Toronto", country: "Canada"),
  Clock(id: "C94", timezone: "America/Vancouver", name: "Vancouver", country: "Canada"),
  Clock(id: "C95", timezone: "America/Winnipeg", name: "Winnipeg", country: "Canada"),
  Clock(id: "C96", timezone: "Antarctica/South_Pole", name: "South Pole", country: "South Pole"),
  Clock(id: "C97", timezone: "Arctic/Longyearbyen", name: "Longyearbyen", country: "Svalbard and Jan Mayen"),
  Clock(id: "C98", timezone: "Asia/Almaty", name: "Almaty", country: "Kazakhstan"),
  Clock(id: "C99", timezone: "Asia/Amman", name: "Amman", country: "Jordan"),
  Clock(id: "C100", timezone: "Asia/Anadyr", name: "Anadyr", country: "Russia"),
  Clock(id: "C101", timezone: "Asia/Aqtau", name: "Aktau", country: "Kazakhstan"),
  Clock(id: "C102", timezone: "Asia/Baghdad", name: "Baghdad", country: "Iraq"),
  Clock(id: "C103", timezone: "Asia/Bahrain", name: "Bahrain", country: "Bahrain"),
  Clock(id: "C104", timezone: "Asia/Baku", name: "Baku", country: "Azerbaijan"),
  Clock(id: "C105", timezone: "Asia/Bangkok", name: "Bangkok", country: "Thailand"),
  Clock(id: "C106", timezone: "Asia/Beirut", name: "Beirut", country: "Lebanon"),
  Clock(id: "C107", timezone: "Asia/Calcutta", name: "Kolkata", country: "India"),
  Clock(id: "C108", timezone: "Asia/Damascus", name: "Damascus", country: "Syria"),
  Clock(id: "C109", timezone: "Asia/Dhaka", name: "Dhaka", country: "Bangladesh"),
  Clock(id: "C110", timezone: "Asia/Dubai", name: "Dubai", country: "United Arab Emirates"),
  Clock(id: "C111", timezone: "Asia/Gaza", name: "Gaza", country: "Palestine"),
  Clock(id: "C112", timezone: "Asia/Hebron", name: "Hebron", country: "Palestine"),
  Clock(id: "C113", timezone: "Asia/Ho_Chi_Minh", name: "Ho Chi Minh", country: "Vietnam"),
  Clock(id: "C114", timezone: "Asia/Hong_Kong", name: "Hong Kong", country: "China"),
  Clock(id: "C115", timezone: "Asia/Jakarta", name: "Jakarta", country: "Indonesia"),
  Clock(id: "C116", timezone: "Asia/Jerusalem", name: "Jerusalem", country: "Israel"),
  Clock(id: "C117", timezone: "Asia/Kabul", name: "Kabul", country: "Afghanistan"),
  Clock(id: "C118", timezone: "Asia/Karachi", name: "Karachi", country: "Pakistan"),
  Clock(id: "C119", timezone: "Asia/Kathmandu", name: "Kathmandu", country: "Nepal"),
  Clock(id: "C120", timezone: "Asia/Kuala_Lumpur", name: "Kuala Lumpur", country: "Malaysia"),
  Clock(id: "C122", timezone: "Asia/Macau", name: "Macau", country: "China"),
  Clock(id: "C123", timezone: "Asia/Manila", name: "Manila", country: "Philippines"),
  Clock(id: "C124", timezone: "Asia/Muscat", name: "Muscat", country: "Oman"),
  Clock(id: "C125", timezone: "Asia/Phnom_Penh", name: "Phnom Penh", country: "Cambodia"),
  Clock(id: "C126", timezone: "Asia/Pyongyang", name: "Pyongyang", country: "North Korea"),
  Clock(id: "C127", timezone: "Asia/Qatar", name: "Qatar", country: "Qatar"),
  Clock(id: "C128", timezone: "Asia/Rangoon", name: "Yangon", country: "Myanmar"),
  Clock(id: "C129", timezone: "Asia/Riyadh", name: "Riyadh", country: "Saudi Arabia"),
  Clock(id: "C130", timezone: "Asia/Seoul", name: "Seoul", country: "South Korea"),
  Clock(id: "C131", timezone: "Asia/Shanghai", name: "Shanghai", country: "China"),
  Clock(id: "C132", timezone: "Asia/Singapore", name: "Singapore", country: "Singapore"),
  Clock(id: "C133", timezone: "Asia/Taipei", name: "Taipei", country: "China"),
  Clock(id: "C134", timezone: "Asia/Tehran", name: "Tehran", country: "Iran"),
  Clock(id: "C135", timezone: "Asia/Tel_Aviv", name: "Tel Aviv", country: "Israel"),
  Clock(id: "C136", timezone: "Asia/Tokyo", name: "Tokyo", country: "Japan"),
  Clock(id: "C137", timezone: "Asia/Ulaanbaatar", name: "Ulaanbaatar", country: "Mongolia"),
  Clock(id: "C138", timezone: "Atlantic/Bermuda", name: "Bermuda", country: "Bermuda"),
  Clock(id: "C139", timezone: "Atlantic/Canary", name: "Canary Islands", country: "Spain"),
  Clock(id: "C140", timezone: "Atlantic/Cape_Verde", name: "Cape Verde", country: "Cape Verde"),
  Clock(id: "C141", timezone: "Atlantic/Reykjavik", name: "Reykjavik", country: "Iceland"),
  Clock(id: "C142", timezone: "Atlantic/Stanley", name: "Stanley", country: "Falkland Islands"),
  Clock(id: "C143", timezone: "Australia/Adelaide", name: "Adelaide", country: "Australia"),
  Clock(id: "C144", timezone: "Australia/Brisbane", name: "Brisbane", country: "Australia"),
  Clock(id: "C145", timezone: "Australia/Canberra", name: "Canberra", country: "Australia"),
  Clock(id: "C146", timezone: "Australia/Darwin", name: "Darwin", country: "Australia"),
  Clock(id: "C147", timezone: "Australia/Melbourne", name: "Melbourne", country: "Australia"),
  Clock(id: "C148", timezone: "Australia/NSW", name: "New South Wales", country: "Australia"),
  Clock(id: "C149", timezone: "Australia/Perth", name: "Perth", country: "Australia"),
  Clock(id: "C150", timezone: "Australia/Queensland", name: "Queensland", country: "Australia"),
  Clock(id: "C151", timezone: "Australia/Sydney", name: "Sydney", country: "Australia"),
  Clock(id: "C152", timezone: "Australia/Victoria", name: "Victoria", country: "Canada"),
  Clock(id: "C153", timezone: "Canada/Newfoundland", name: "Newfoundland", country: "Canada"),
  Clock(id: "C154", timezone: "Canada/Saskatchewan", name: "Saskatchewan", country: "Canada"),
  Clock(id: "C155", timezone: "Chile/EasterIsland", name: "Easter Island", country: "Chile"),
  Clock(id: "C156", timezone: "Europe/Amsterdam", name: "Amsterdam", country: "Netherlands"),
  Clock(id: "C157", timezone: "Europe/Andorra", name: "Andorra", country: "Andorra"),
  Clock(id: "C159", timezone: "Europe/Belfast", name: "Belfast", country: "United Kingdom"),
  Clock(id: "C160", timezone: "Europe/Belgrade", name: "Belgrade", country: "Serbia"),
  Clock(id: "C161", timezone: "Europe/Berlin", name: "Berlin", country: "Germany"),
  Clock(id: "C162", timezone: "Europe/Bratislava", name: "Bratislava", country: "Slovakia"),
  Clock(id: "C163", timezone: "Europe/Brussels", name: "Brussels", country: "Belgium"),
  Clock(id: "C164", timezone: "Europe/Bucharest", name: "Bucharest", country: "Romania"),
  Clock(id: "C165", timezone: "Europe/Budapest", name: "Budapest", country: "Hungary"),
  Clock(id: "C166", timezone: "Europe/Chisinau", name: "Chisinau", country: "Moldova"),
  Clock(id: "C167", timezone: "Europe/Copenhagen", name: "Copenhagen", country: "Denmark"),
  Clock(id: "C168", timezone: "Europe/Dublin", name: "Dublin", country: "Ireland"),
  Clock(id: "C169", timezone: "Europe/Gibraltar", name: "Gibraltar", country: "Gibraltar"),
  Clock(id: "C170", timezone: "Europe/Helsinki", name: "Helsinki", country: "Finland"),
  Clock(id: "C171", timezone: "Europe/Isle_of_Man", name: "Isle of Man", country: "Isle of Man"),
  Clock(id: "C172", timezone: "Europe/Istanbul", name: "Istanbul", country: "Türkiye"),
  Clock(id: "C173", timezone: "Europe/Lisbon", name: "Lisbon", country: "Portugal"),
  Clock(id: "C174", timezone: "Europe/London", name: "London", country: "United Kingdom"),
  Clock(id: "C175", timezone: "Europe/Luxembourg", name: "Luxembourg", country: "Luxembourg"),
  Clock(id: "C176", timezone: "Europe/Madrid", name: "Madrid", country: "Spain"),
  Clock(id: "C177", timezone: "Europe/Malta", name: "Malta", country: "Malta"),
  Clock(id: "C178", timezone: "Europe/Minsk", name: "Minsk", country: "Belarus"),
  Clock(id: "C179", timezone: "Europe/Monaco", name: "Monaco", country: "Monaco"),
  Clock(id: "C180", timezone: "Europe/Moscow", name: "Moscow", country: "Russia"),
  Clock(id: "C181", timezone: "Europe/Oslo", name: "Oslo", country: "Norway"),
  Clock(id: "C182", timezone: "Europe/Paris", name: "Paris", country: "France"),
  Clock(id: "C183", timezone: "Europe/Prague", name: "Prague", country: "Czechia"),
  Clock(id: "C184", timezone: "Europe/Riga", name: "Riga", country: "Latvia"),
  Clock(id: "C185", timezone: "Europe/Rome", name: "Rome", country: "Italy"),
  Clock(id: "C186", timezone: "Europe/San_Marino", name: "San Marino", country: "San Marino"),
  Clock(id: "C187", timezone: "Europe/Sarajevo", name: "Sarajevo", country: "Bosnia and Herzegovina"),
  Clock(id: "C188", timezone: "Europe/Simferopol", name: "Simferopol", country: "Ukraine"),
  Clock(id: "C189", timezone: "Europe/Skopje", name: "Skopje", country: "North Macedonia"),
  Clock(id: "C190", timezone: "Europe/Sofia", name: "Sofia", country: "Bulgaria"),
  Clock(id: "C191", timezone: "Europe/Stockholm", name: "Stockholm", country: "Sweden"),
  Clock(id: "C192", timezone: "Europe/Tallinn", name: "Tallinn", country: "Estonia"),
  Clock(id: "C193", timezone: "Europe/Vatican", name: "Vatican", country: "Vatican"),
  Clock(id: "C194", timezone: "Europe/Vienna", name: "Vienna", country: "Austria"),
  Clock(id: "C195", timezone: "Europe/Vilnius", name: "Vilnius", country: "Lithuania"),
  Clock(id: "C197", timezone: "Europe/Warsaw", name: "Warsaw", country: "Poland"),
  Clock(id: "C198", timezone: "Europe/Zagreb", name: "Zagreb", country: "Croatia"),
  Clock(id: "C199", timezone: "Europe/Zurich", name: "Zurich", country: "Switzerland"),
  Clock(id: "C200", timezone: "Indian/Maldives", name: "Maldives", country: "Maldives"),
  Clock(id: "C201", timezone: "Indian/Mauritius", name: "Mauritius", country: "Mauritius"),
  Clock(id: "C202", timezone: "Pacific/Auckland", name: "Auckland", country: "New Zealand"),
  Clock(id: "C203", timezone: "Pacific/Fiji", name: "Fiji", country: "Fiji"),
  Clock(id: "C204", timezone: "Pacific/Guam", name: "Guam", country: "Guam"),
  Clock(id: "C205", timezone: "Pacific/Honolulu", name: "Honolulu", country: "United States"),
  Clock(id: "C206", timezone: "Australia/Kiritimati", name: "Kiritimati", country: "Australia"),
  Clock(id: "C207", timezone: "Pacific/Noumea", name: "Noumea", country: "New Caledonia"),
  Clock(id: "C208", timezone: "Pacific/Samoa", name: "Samoa", country: "Samoa"),
  Clock(id: "C209", timezone: "Pacific/Tahiti", name: "Tahiti", country: "French Polynesia"),
  Clock(id: "C210", timezone: "America/Antigua", name: "Antigua", country: "Antigua and Barbuda"),
  Clock(id: "C211", timezone: "America/Chicago", name: "Austin", country: "United States"),
  Clock(id: "C212", timezone: "America/New_York", name: "Boston", country: "United States"),
  Clock(id: "C213", timezone: "America/Denver", name: "Calgary", country: "Canada"),
  Clock(id: "C214", timezone: "America/New_York", name: "Columbus", country: "United States"),
  Clock(id: "C215", timezone: "America/Chicago", name: "Dallas", country: "United States"),
  Clock(id: "C216", timezone: "America/New_York", name: "Knoxville", country: "United States"),
  Clock(id: "C217", timezone: "America/Chicago", name: "Memphis", country: "United States"),
  Clock(id: "C218", timezone: "America/New_York", name: "Miami", country: "United States"),
  Clock(id: "C219", timezone: "America/Chicago", name: "Minneapolis", country: "United States"),
  Clock(id: "C220", timezone: "America/New_York", name: "Ottawa", country: "Canada"),
  Clock(id: "C221", timezone: "America/New_York", name: "Philadelphia", country: "United States"),
  Clock(id: "C222", timezone: "America/Los_Angeles", name: "Portland", country: "United States"),
  Clock(id: "C223", timezone: "America/Los_Angeles", name: "San Diego", country: "United States"),
  Clock(id: "C224", timezone: "America/Los_Angeles", name: "San Francisco", country: "United States"),
  Clock(id: "C225", timezone: "America/Denver", name: "Salt Lake City", country: "United States"),
  Clock(id: "C226", timezone: "America/Los_Angeles", name: "San José", country: "United States"),
  Clock(id: "C227", timezone: "America/Guatemala", name: "San Salvador", country: "El Salvador"),
  Clock(id: "C228", timezone: "America/Los_Angeles", name: "Seattle", country: "United States"),
  Clock(id: "C229", timezone: "America/Chicago", name: "St. Louis", country: "United States"),
  Clock(id: "C230", timezone: "America/New_York", name: "Washington D.C.", country: "United States"),
  Clock(id: "C231", timezone: "America/Chicago", name: "Houston", country: "United States"),
  Clock(id: "C232", timezone: "America/Chicago", name: "San Antonio", country: "United States"),
  Clock(id: "C233", timezone: "America/New_York", name: "Jacksonville", country: "United States"),
  Clock(id: "C234", timezone: "America/New_York", name: "Baltimore", country: "United States"),
  Clock(id: "C235", timezone: "America/Chicago", name: "Nashville", country: "United States"),
  Clock(id: "C236", timezone: "America/Chicago", name: "Milwaukee", country: "United States"),
  Clock(id: "C237", timezone: "America/Chicago", name: "Oklahoma City", country: "United States"),
  Clock(id: "C238", timezone: "America/Los_Angeles", name: "Las Vegas", country: "United States"),
  Clock(id: "C239", timezone: "America/Denver", name: "Albuquerque", country: "United States"),
  Clock(id: "C240", timezone: "MST", name: "Tucson", country: "United States"),
  Clock(id: "C241", timezone: "America/Los_Angeles", name: "Sacramento", country: "United States"),
  Clock(id: "C242", timezone: "America/New_York", name: "Atlanta", country: "United States"),
  Clock(id: "C243", timezone: "America/New_York", name: "Cleveland", country: "United States"),
  Clock(id: "C244", timezone: "America/Chicago", name: "New Orleans", country: "United States"),
  Clock(id: "C245", timezone: "America/New_York", name: "Tampa", country: "United States"),
  Clock(id: "C246", timezone: "America/New_York", name: "Pittsburgh", country: "United States"),
  Clock(id: "C247", timezone: "America/New_York", name: "Cincinnati", country: "United States"),
  Clock(id: "C248", timezone: "America/Los_Angeles", name: "Mountain View", country: "United States"),
  Clock(id: "C249", timezone: "America/Los_Angeles", name: "Reno", country: "United States"),
  Clock(id: "C250", timezone: "America/Los_Angeles", name: "Black Rock City", country: "United States"),
  Clock(id: "C251", timezone: "Asia/Riyadh", name: "Doha", country: "Qatar"),
  Clock(id: "C252", timezone: "Asia/Shanghai", name: "Beijing", country: "China"),
  Clock(id: "C253", timezone: "Asia/Kolkata", name: "Mumbai", country: "India"),
  Clock(id: "C254", timezone: "Asia/Kolkata", name: "Delhi", country: "India"),
  Clock(id: "C255", timezone: "Asia/Tokyo", name: "Osaka", country: "Japan"),
  Clock(id: "C256", timezone: "Asia/Karachi", name: "Lahore", country: "Pakistan"),
  Clock(id: "C257", timezone: "Asia/Riyadh", name: "Sana\'a", country: "Yemen"),
  Clock(id: "C258", timezone: "Europe/Madrid", name: "Barcelona", country: "Spain"),
  Clock(id: "C259", timezone: "Europe/Berlin", name: "Munich", country: "Germany"),
  Clock(id: "C260", timezone: "Europe/Rome", name: "Milan", country: "Italy"),
  Clock(id: "C261", timezone: "Europe/Berlin", name: "Frankfurt", country: "Germany"),
  Clock(id: "C262", timezone: "Asia/Bangkok", name: "Hanoi", country: "Vietnam"),
  Clock(id: "C263", timezone: "Europe/Istanbul", name: "Ankara", country: "Türkiye"),
  Clock(id: "C264", timezone: "Asia/Kolkata", name: "Bangalore", country: "India"),
  Clock(id: "C265", timezone: "America/Sao_Paulo", name: "Brasília", country: "Brazil"),
  Clock(id: "C266", timezone: "Africa/Johannesburg", name: "Cape Town", country: "South Africa"),
  Clock(id: "C267", timezone: "Asia/Karachi", name: "Islamabad", country: "Pakistan"),
  Clock(id: "C268", timezone: "America/Sao_Paulo", name: "Rio de Janeiro", country: "Brazil"),
  Clock(id: "C269", timezone: "America/Detroit", name: "Ann Arbor", country: "United States"),
  Clock(id: "C270", timezone: "America/Denver", name: "Boulder", country: "United States"),
  Clock(id: "C271", timezone: "Europe/London", name: "Cambridge", country: "United Kingdom"),
  Clock(id: "C272", timezone: "America/Los_Angeles", name: "Kirkland", country: "United States"),
  Clock(id: "C273", timezone: "America/Chicago", name: "Madison", country: "United States"),
  Clock(id: "C274", timezone: "Asia/Shanghai", name: "Guangzhou", country: "China"),
  Clock(id: "C275", timezone: "Asia/Kolkata", name: "Hyderabad", country: "India"),
  Clock(id: "C276", timezone: "America/New_York", name: "Reston", country: "United States"),
  Clock(id: "C277", timezone: "America/Sao_Paulo", name: "Belo Horizonte", country: "Brazil"),
  Clock(id: "C278", timezone: "America/Santiago", name: "Santiago", country: "United States"),
  Clock(id: "C279", timezone: "Africa/Monrovia", name: "Monrovia", country: "Liberia"),
  Clock(id: "C280", timezone: "Asia/Colombo", name: "Colombo", country: "Sri Lanka"),
  Clock(id: "C281", timezone: "America/Chihuahua", name: "Chihuahua", country: "Mexico"),
  Clock(id: "C282", timezone: "Asia/Kolkata", name: "Gurgaon", country: "India"),
  Clock(id: "C283", timezone: "Europe/London", name: "Manchester", country: "United Kingdom"),
  Clock(id: "C284", timezone: "Europe/Bucharest", name: "Kyiv", country: "Ukraine"),
  Clock(id: "C285", timezone: "Europe/Moscow", name: "St. Petersburg", country: "Russia"),
  Clock(id: "C286", timezone: "Europe/Warsaw", name: "Kraków", country: "Poland"),
  Clock(id: "C287", timezone: "Europe/Warsaw", name: "Wroclaw", country: "Poland"),
  Clock(id: "C288", timezone: "Europe/Berlin", name: "Hamburg", country: "Germany"),
  Clock(id: "C289", timezone: "Europe/Bucharest", name: "Oulu", country: "Finland"),
  Clock(id: "C290", timezone: "Asia/Jerusalem", name: "Haifa", country: "Israel"),
  Clock(id: "C291", timezone: "America/Puerto_Rico", name: "San Juan", country: "Puerto Rico"),
  Clock(id: "C292", timezone: "America/Tegucigalpa", name: "Tegucigalpa", country: "Honduras"),
  Clock(id: "C293", timezone: "America/Paramaribo", name: "Paramaribo", country: "Suriname"),
  Clock(id: "C294", timezone: "America/Panama", name: "Quito", country: "Ecuador"),
  Clock(id: "C295", timezone: "Pacific/Honolulu", name: "Hawaii", country: "United States"),
  Clock(id: "C296", timezone: "America/Anchorage", name: "Alaska", country: "United States"),
  Clock(id: "C297", timezone: "America/Phoenix", name: "Phoenix", country: "United States"),
  Clock(id: "C299", timezone: "America/Jamaica", name: "Kingston", country: "Canada"),
  Clock(id: "C300", timezone: "Atlantic/Cape_Verde", name: "Praia", country: "Cape Verde"),
  Clock(id: "C301", timezone: "Atlantic/Reykjavik", name: "Reykjavik", country: "Iceland"),
  Clock(id: "C302", timezone: "Europe/Zurich", name: "Geneva", country: "Switzerland"),
  Clock(id: "C303", timezone: "Africa/Windhoek", name: "Windhoek", country: "Namibia"),
  Clock(id: "C304", timezone: "Europe/Sofia", name: "Sofia", country: "Bulgaria"),
  Clock(id: "C305", timezone: "Europe/Athens", name: "Athens", country: "Greece"),
  Clock(id: "C306", timezone: "Europe/Kaliningrad", name: "Kaliningrad", country: "Russia"),
  Clock(id: "C307", timezone: "Africa/Khartoum", name: "Khartoum", country: "Sudan"),
  Clock(id: "C308", timezone: "Africa/Nairobi", name: "Nairobi", country: "Kenya"),
  Clock(id: "C309", timezone: "Asia/Aden", name: "Aden", country: "Yemen"),
  Clock(id: "C310", timezone: "Indian/Antananarivo", name: "Antananarivo", country: "Madagascar"),
  Clock(id: "C311", timezone: "Asia/Kuwait", name: "Kuwait", country: "Kuwait"),
  Clock(id: "C312", timezone: "Asia/Dubai", name: "Abu Dhabi", country: "United Arab Emirates"),
  Clock(id: "C313", timezone: "Europe/Samara", name: "Samara", country: "Russia"),
  Clock(id: "C314", timezone: "Asia/Kolkata", name: "New Delhi", country: "India"),
  Clock(id: "C315", timezone: "Asia/Novosibirsk", name: "Novosibirsk", country: "Russia"),
  Clock(id: "C316", timezone: "Asia/Taipei", name: "Taiwan", country: "China"),
  Clock(id: "C317", timezone: "Asia/Irkutsk", name: "Irkutsk", country: "Russia"),
  Clock(id: "C318", timezone: "Asia/Chita", name: "Chita", country: "Russia"),
  Clock(id: "C319", timezone: "Asia/Vladivostok", name: "Vladivostok", country: "Russia"),
  Clock(id: "C321", timezone: "Asia/Magadan", name: "Magadan", country: "Russia"),
  Clock(id: "C322", timezone: "Asia/Kamchatka", name: "Kamchatka", country: "Russia"),
  Clock(id: "C323", timezone: "Pacific/Fiji", name: "Suva", country: "Fiji"),
  Clock(id: "C325", timezone: "Pacific/Auckland", name: "Wellington", country: "New Zealand"),
];
